FROM archlinux:latest AS builder

# 设置官方镜像源, 保证不会 404
RUN echo 'Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist \
    && pacman -Sy --noconfirm reflector \
    && reflector --protocol https --country China --sort rate --save /etc/pacman.d/mirrorlist \
    && pacman -Syy --noconfirm

# 安装构建工具, Python, Pybind11
RUN pacman -Syu --needed --noconfirm \
    git base-devel sudo wget unzip cmake clang taglib python python-pip pybind11 openssl

# 创建makepkg用户(构建AUR包)
ARG user=makepkg
RUN useradd --system --create-home $user \
    && echo "$user ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/$user
USER $user
WORKDIR /home/$user

# 安装 yay (AUR 包管理器)
RUN git clone https://aur.archlinux.org/yay.git \
    && cd yay \
    && makepkg -sri --needed --noconfirm \
    && cd .. && rm -rf yay .cache

# 安装 Aegisub
RUN yay -S --noconfirm aegisub

# 克隆 HX-Music
RUN git clone https://github.com/HengXin666/HX-Music.git HX-Music

# 复制 Lua 脚本
RUN mkdir -p /usr/share/aegisub/automation/autoload/ \
    && sudo cp HX-Music/pyTool/lua/set-karaoke-style.lua /usr/share/aegisub/automation/autoload/

# 安装 uv
RUN pip install --break-system-packages uv
ENV PATH="/home/makepkg/.local/bin:$PATH"

# 初始化 uv 虚拟环境
WORKDIR /home/$user/HX-Music/pyTool
RUN uv sync

# 测试使用
RUN uv run main.py 

# 使用runtime Python, 无需复制虚拟环境
RUN uv python pin

WORKDIR /home/$user/HX-Music
RUN git submodule update --init --recursive

# 构建 HX-Music-Server, 并指定 Python 环境
WORKDIR /home/$user/HX-Music/build
RUN cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_CLIENT=OFF \
    -DBUILD_SERVER=ON \
    -DPYTHON_EXECUTABLE=/home/makepkg/HX-Music/pyTool/.venv/bin/python3 \
    -DPYTHON_INCLUDE_DIR=/home/makepkg/HX-Music/pyTool/.venv/include/python3.13 \
    -DPYTHON_LIBRARY=/home/makepkg/HX-Music/pyTool/.venv/lib/libpython3.13.so

RUN cmake --build . --config Release --target HX-Music-Server --

# 清理不需要的构建文件和AUR工具
RUN sudo pacman -Rns --noconfirm base-devel yay \
    && sudo pacman -Sc --noconfirm \
    && rm -rf /home/makepkg/.cache

# 暴露端口和数据目录
RUN mkdir -p /home/$user/HX-Music/data
VOLUME ["/home/makepkg/HX-Music"]
EXPOSE 28205

# 设置工作目录
WORKDIR /home/$user/HX-Music/build/HX-Music-Server

# 启动
CMD ["uv", "run", "./HX-Music-Server"]
